matrix:
- name: Markdown
  sources:
  - '**/*.md'
  aspell:
    lang: de
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
    - pyspelling.filters.markdown:
    - pyspelling.filters.url: