services:
   mongodb:
    image: mongo:7.0.40
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MONGOT_LOG_FILE=/dev/log
      - RUNNER_LOG_FILE=/dev/log
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - mongodb_network
    logging:
      driver: "json-file"

   backend:
    build: ./backend
    container_name: gymetrics
    environment:
      - MONGODB_URI=mongodb://${DATABASE_ROOT_USERNAME}:${DATABASE_ROOT_PASSWORD}@mongodb:27017/${APP_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH=${JWT_REFRESH}
      - SCRAPER_API_KEY=${SCRAPER_API_KEY}
      - MODE=AI
      - OLLAMA_URL=http://192.168.68.104:11434
      - OLLAMA_MODEL=ministral-3:3b
      - ENABLE_SCRAPER=true
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    restart: on-failure
  
   python-scraper:
    build: ./scrapeService
    container_name: gymetrics-scraper
    environment:
      - SCRAPER_API_KEY=${SCRAPER_API_KEY}
    ports:
      - 5000:5000
    networks:
      - mongodb_network
    restart: unless-stopped
    
   mcp-server:
    build: ./mcpServer
    container_name: mcp-server
    restart: always
    ports:
      - 3001:3001
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - mongodb_network
    
networks:
  mongodb_network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
